const { NewCar } = require("@classlibrary/core-js");
const car = new NewCar(10, 10);
car.start();
car.drive(18);
car.drive(26);
car.drive(10);
car.drive(10);
car.drive(30);
car.drive(14);
car.drive(10);
car.drive(0);
